name: Cross-compile LLVM 19 for macOS 12 on Ubuntu 2-core runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang llvm

    - name: Install osxcross
      run: |
        git clone https://github.com/tpoechtrager/osxcross.git
        cd osxcross
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
        mv MacOSX11.3.sdk.tar.xz tarballs/
        UNATTENDED=yes OSX_VERSION_MIN=10.12 ./build.sh

    - name: Set up osxcross
      run: |
        echo "$(pwd)/osxcross/target/bin" >> $GITHUB_PATH
        echo "OSXCROSS_MP_INC=$(pwd)/osxcross/target/macports/pkgs/opt/local/include" >> $GITHUB_ENV

    - name: Cross-compile LLVM 19 for macOS
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$(pwd)/../osxcross/target/macports/pkgs/opt/local/lib/cmake/llvm/LLVMConfig.cmake -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release /home/runner/llvm
        make -j$(nproc)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: llvm-19-macos-build
        path: build